services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DEEPSEEK_API_KEY=sk-ccc37a109afb461989af8cf994a8bc60
    volumes:
      - /mnt/c/Users/fvegi/dev/pgi-ia/backend:/app/backend
      - /mnt/c/Users/fvegi/dev/pgi-ia/frontend:/app/frontend

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html